### ISSUE TITLE
date issues

### ISSUE THREAD

**Issue by carlokok** [remobjects/script#5]
Script doesn't parse iso8601 dates in the Date() constrcutor, UTC() (and date) should allow passing minutes/seconds etc > 60 which denotes the next build.

**Comment by sp00x** [comment]
new Date().toUTCString() is "broken" also, at least if you expect it to work as most JS implementations do. I notice the EcmaScript spec (15.9.5.42 Date.prototype.toUTCString) doesn't really say how it's supposed to look, but:

ROS:
  new Date().toUTCString(); -> "03/11/2015 14:26:06"

Most browsers, Node.js etc:
  "Wed, 11 Mar 2015 14:26:47 GMT" // RFC-822 , RFC-1123

**Comment by sp00x** [comment]
Date() constructor is also supposed to take milliseconds-since-epoch as input, not seconds..

**Comment by sp00x** [comment]
a date  .getDay() and .getUTCDay()  returns e.g. "Wednesday" (.Net enum?) instead of 0..6 
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.6
